import type { QuranAudioConfig } from './types';

export const quranAudioMalayalam: QuranAudioConfig = {
  baseUrl: 'https://archive.org/download/malayalam-meal/',
  shareText: `Quran Malayalam, app for those who love to listen, Quran Malayalam meaning

 iOS: https://itunes.apple.com/in/app/quran-audio-malayalam/id1607731815?mt=8

 MacOS:macappstore://itunes.apple.com/in/app/quran-audio-malayalam/id1607731815?mt=8`,
  mail: {
    subject: 'Quran Audio Malayalam - iPhone',
    to: ['abidkuwaitamani@gmail.com', 'abuabdullah.sed@gmail.com'],
  },
  chapters: [
    {
      index: 1,
      name: 'سورَة ٱلْفَاتِحَة',
      nameTrans: 'Surah Al-Fatihah',
      nameMl: 'അല്‍ ഫാത്തിഹ',
      fileName: '000_Al_Fattiha.mp3',
      size: '767.8K',
      durationInSecs: 98,
    },
    {
      index: 2,
      name: 'سورَة ٱلْبَقَرَة',
      nameTrans: 'Surah Al-Baqarah',
      nameMl: 'അല്‍ ബഖറ',
      fileName: '002_Al_Baqarah.mp3',
      size: '108.9M',
      durationInSecs: 14275,
    },
    {
      index: 3,
      name: 'سورَة آلِ عِمْرَان',
      nameTrans: "Surah Ali 'Imran",
      nameMl: 'ആലു ഇംറാന്‍',
      fileName: '003_Al_Imran.mp3',
      size: '56.5M',
      durationInSecs: 7405,
    },
    {
      index: 4,
      name: 'سورَة ٱلنِّسَاء',
      nameTrans: 'Surah An-Nisa',
      nameMl: 'അന്നിസാഅ്',
      fileName: '004_An_Nisa.mp3',
      size: '66.4M',
      durationInSecs: 8702,
    },
    {
      index: 5,
      name: 'سورَة ٱلْمَائِدَة',
      nameTrans: "Surah Al-Ma'idah",
      nameMl: 'അല്‍ മാഇദഃ',
      fileName: '005_Al_Maeda.mp3',
      size: '44.4M',
      durationInSecs: 5824,
    },
    {
      index: 6,
      name: 'سورَة ٱلْأَنْعَام',
      nameTrans: "Surah Al-An'am",
      nameMl: 'അല്‍ അന്‍ആം',
      fileName: '006_Al_Anam.mp3',
      size: '49.5M',
      durationInSecs: 6483,
    },
    {
      index: 7,
      name: 'سورَة ٱلْأَعْرَاف',
      nameTrans: "Surah Al-A'raf",
      nameMl: 'അല്‍ അഅ്റാഫ്',
      fileName: '007_Al_Araf.mp3',
      size: '63.3M',
      durationInSecs: 8300,
    },
    {
      index: 8,
      name: 'سورَة ٱلْأَنْفَال',
      nameTrans: 'Surah Al-Anfal',
      nameMl: 'അല്‍ അന്‍ഫാല്‍',
      fileName: '008_Al_Anfal.mp3',
      size: '20.7M',
      durationInSecs: 2719,
    },
    {
      index: 9,
      name: 'سورَة ٱلتَّوْبَة',
      nameTrans: 'Surah At-Tawbah',
      nameMl: 'അത്തൌബ',
      fileName: '009_At_Touba.mp3',
      size: '42.0M',
      durationInSecs: 5499,
    },
    {
      index: 10,
      name: 'سورَة يُونُس',
      nameTrans: 'Surah Yunus',
      nameMl: 'യൂനുസ്',
      fileName: '010_Yunus.mp3',
      size: '29.8M',
      durationInSecs: 3907,
    },
    {
      index: 11,
      name: 'سورَة هُود',
      nameTrans: 'Surah Hud',
      nameMl: 'ഹൂദ്',
      fileName: '011_Hud.mp3',
      size: '32.8M',
      durationInSecs: 4305,
    },
    {
      index: 12,
      name: 'سورَة يُوسُف',
      nameTrans: 'Surah Yusuf',
      nameMl: 'യൂസുഫ്',
      fileName: '012_Yusuf.mp3',
      size: '28.9M',
      durationInSecs: 3786,
    },
    {
      index: 13,
      name: 'سورَة ٱلرَّعْد',
      nameTrans: "Surah Ar-Ra'd",
      nameMl: 'അര്‍റഅ്ദ്',
      fileName: '013_Ar_Raad.mp3',
      size: '15.2M',
      durationInSecs: 1987,
    },
    {
      index: 14,
      name: 'سورَة إِبْرَاهِيم',
      nameTrans: 'Surah Ibrahim',
      nameMl: 'ഇബ്രാഹീം',
      fileName: '014_Ibrahim.mp3',
      size: '952.7K',
      durationInSecs: 121,
    },
    {
      index: 15,
      name: 'سورَة ٱلْحِجْر',
      nameTrans: 'Surah Al-Hijr',
      nameMl: 'അല്‍ ഹിജ്ര്‍',
      fileName: '015_Al_Hijr.mp3',
      size: '13.6M',
      durationInSecs: 1780,
    },
    {
      index: 16,
      name: 'سورَة ٱلنَّحْل',
      nameTrans: 'Surah An-Nahl',
      nameMl: 'അന്നഹ്ല്‍',
      fileName: '016_An_Nahl.mp3',
      size: '33.4M',
      durationInSecs: 4380,
    },
    {
      index: 17,
      name: 'سورَة ٱلْإِسْرَاء',
      nameTrans: 'Surah Al-Isra',
      nameMl: 'അല്‍ ഇസ്റാഅ്',
      fileName: '017_Al_Isra.mp3',
      size: '27.1M',
      durationInSecs: 3554,
    },
    {
      index: 18,
      name: 'سورَة ٱلْكَهْف',
      nameTrans: 'Surah Al-Kahf',
      nameMl: 'അല്‍ കഹ്ഫ്',
      fileName: '018_Al_Kahf.mp3',
      size: '25.9M',
      durationInSecs: 3388,
    },
    {
      index: 19,
      name: 'سورَة مَرْيَم',
      nameTrans: 'Surah Maryam',
      nameMl: 'മര്‍യം',
      fileName: '019_Maryam.mp3',
      size: '18.0M',
      durationInSecs: 2364,
    },
    {
      index: 20,
      name: 'سورَة طه',
      nameTrans: 'Surah Ta-Ha',
      nameMl: 'ത്വാഹാ',
      fileName: '020_Taha.mp3',
      size: '24.3M',
      durationInSecs: 3189,
    },
    {
      index: 21,
      name: 'سورَة ٱلْأَنْبِيَاء',
      nameTrans: 'Surah Al-Anbiya',
      nameMl: 'അല്‍ അന്‍ബിയാഅ്',
      fileName: '021_Al_Anbiya.mp3',
      size: '20.8M',
      durationInSecs: 2724,
    },
    {
      index: 22,
      name: 'سورَة ٱلْحَجّ',
      nameTrans: 'Surah Al-Hajj',
      nameMl: 'അല്‍ ഹജ്ജ്',
      fileName: '022_Al_Hajj.mp3',
      size: '21.4M',
      durationInSecs: 2811,
    },
    {
      index: 23,
      name: 'سورَة ٱلْمُؤْمِنُون',
      nameTrans: "Surah Al-Mu'minun",
      nameMl: 'അല്‍ മുഅ്മിനൂന്‍',
      fileName: '023_Al_Muminoom.mp3',
      size: '18.4M',
      durationInSecs: 2414,
    },
    {
      index: 24,
      name: 'سورَة ٱلنُّور',
      nameTrans: 'Surah An-Nur',
      nameMl: 'അന്നൂര്‍',
      fileName: '024_An_Nur.mp3',
      size: '21.5M',
      durationInSecs: 2812,
    },
    {
      index: 25,
      name: 'سورَة ٱلْفُرْقَان',
      nameTrans: 'Surah Al-Furqan',
      nameMl: 'അല്‍ ഫുര്‍ഖാന്‍',
      fileName: '025_Al_Furqan.mp3',
      size: '1.4M',
      durationInSecs: 178,
    },
    {
      index: 26,
      name: 'سورَة ٱلشُّعَرَاء',
      nameTrans: "Surah Ash-Shu'ara",
      nameMl: 'അശ്ശുഅറാഅ്',
      fileName: '026_Ash_Shuara.mp3',
      size: '23.5M',
      durationInSecs: 3080,
    },
    {
      index: 27,
      name: 'سورَة ٱلنَّمْل',
      nameTrans: 'Surah An-Naml',
      nameMl: 'അന്നംല്‍',
      fileName: '027_An_Naml.mp3',
      size: '19.4M',
      durationInSecs: 2546,
    },
    {
      index: 28,
      name: 'سورَة ٱلْقَصَص',
      nameTrans: 'Surah Al-Qasas',
      nameMl: 'അല്‍ ഖസസ്',
      fileName: '028_Al_Qasas.mp3',
      size: '24.2M',
      durationInSecs: 3178,
    },
    {
      index: 29,
      name: 'سورَة ٱلْعَنْكَبُوت',
      nameTrans: 'Surah Al-Ankabut',
      nameMl: 'അല്‍ അന്‍കബൂത്',
      fileName: '029_Al_Ankaboot.mp3',
      size: '15.9M',
      durationInSecs: 2090,
    },
    {
      index: 30,
      name: 'سورَة ٱلرُّوم',
      nameTrans: 'Surah Ar-Rum',
      nameMl: 'അര്‍റൂം',
      fileName: '030_Ar_Rum.mp3',
      size: '13.9M',
      durationInSecs: 1818,
    },
    {
      index: 31,
      name: 'سورَة لُقْمَان',
      nameTrans: 'Surah Luqmaan',
      nameMl: 'ലുഖ്മാന്‍',
      fileName: '031_Luqman.mp3',
      size: '9.3M',
      durationInSecs: 1215,
    },
    {
      index: 32,
      name: 'سورَة ٱلسَّجْدَة',
      nameTrans: 'As-Sajdah',
      nameMl: 'അസ്സജദഃ',
      fileName: '032_As_Sajada.mp3',
      size: '6.2M',
      durationInSecs: 818,
    },
    {
      index: 33,
      name: 'سورَة ٱلْأَحْزَاب',
      nameTrans: 'Al-Ahzaab',
      nameMl: 'അല്‍ അഹ്സാബ്',
      fileName: '033_Al_Ahzab.mp3',
      size: '22.5M',
      durationInSecs: 2943,
    },
    {
      index: 34,
      name: 'سورَة سَبَأ',
      nameTrans: 'Surah Saba (surah)',
      nameMl: 'സബഅ്',
      fileName: '034_Saba.mp3',
      size: '14.2M',
      durationInSecs: 1861,
    },
    {
      index: 35,
      name: 'سورَة فَاطِر',
      nameTrans: 'Surah Faatir',
      nameMl: 'ഫാത്വിര്‍',
      fileName: '035_Fatir.mp3',
      size: '12.2M',
      durationInSecs: 1595,
    },
    {
      index: 36,
      name: 'سورَة يس',
      nameTrans: 'Surah Ya-Sin',
      nameMl: 'യാസീന്‍',
      fileName: '036_Yasin.mp3',
      size: '13.3M',
      durationInSecs: 1738,
    },
    {
      index: 37,
      name: 'سورَة ٱلصَّافَّات',
      nameTrans: 'Surah As-Saaffaat',
      nameMl: 'അസ്സ്വാഫ്ഫാത്ത്',
      fileName: '037_As-Saffat.mp3',
      size: '17.0M',
      durationInSecs: 2234,
    },
    {
      index: 38,
      name: 'سورَة ص',
      nameTrans: 'Surah Saad',
      nameMl: 'സ്വാദ്',
      fileName: '038_Sad.mp3',
      size: '13.1M',
      durationInSecs: 1721,
    },
    {
      index: 39,
      name: 'سورَة ٱلزُّمَر',
      nameTrans: 'Surah Az-Zumar',
      nameMl: 'അസ്സുമര്‍',
      fileName: '039_Az_Zumar.mp3',
      size: '19.9M',
      durationInSecs: 2612,
    },
    {
      index: 40,
      name: 'سورَة غَافِ',
      nameTrans: 'Surah Ghafir',
      nameMl: 'അല്‍ മുഅ്മിന്‍',
      fileName: '040_Ghafir.mp3',
      size: '20.3M',
      durationInSecs: 2661,
    },
    {
      index: 41,
      name: 'سورَة فُصِّلَت',
      nameTrans: 'Surah Fussilat',
      nameMl: 'ഫുസ്സിലത്ത്',
      fileName: '041_Fussilat.mp3',
      size: '14.5M',
      durationInSecs: 1898,
    },
    {
      index: 42,
      name: 'سورَة ٱلشُّورىٰ',
      nameTrans: 'Surah Ash-Shura',
      nameMl: 'അശ്ശൂറാ',
      fileName: '042_Ash_Shura.mp3',
      size: '15.1M',
      durationInSecs: 1975,
    },
    {
      index: 43,
      name: 'سورَة ٱلْزُّخْرُف',
      nameTrans: 'Surah Az-Zukhruf',
      nameMl: 'അസ്സുഖ്റുഫ്',
      fileName: '043_Az_Zukuruf.mp3',
      size: '16.3M',
      durationInSecs: 2132,
    },
    {
      index: 44,
      name: 'سورَة ٱلدُّخَان',
      nameTrans: 'Surah Ad-Dukhaan',
      nameMl: 'അദ്ദുഖാന്‍',
      fileName: '044_Adh_Dhukhan.mp3',
      size: '6.9M',
      durationInSecs: 904,
    },
    {
      index: 45,
      name: 'سورَة ٱلْجَاثِيَة',
      nameTrans: 'Surah Al-Jaathiyah',
      nameMl: 'അല്‍ ജാഥിയഃ',
      fileName: '045_Al_Jathiya.mp3',
      size: '8.1M',
      durationInSecs: 1060,
    },
    {
      index: 46,
      name: 'سورَة ٱلْأَحْقَاف',
      nameTrans: 'Surah Al-Ahqaaf',
      nameMl: 'അല്‍ അഹ്ഖാഫ്',
      fileName: '046_Al_Ahqaf.mp3',
      size: '10.4M',
      durationInSecs: 1362,
    },
    {
      index: 47,
      name: 'سورَة مُحَمَّد',
      nameTrans: 'Surah Muhammad',
      nameMl: 'മുഹമ്മദ്',
      fileName: '047_Mohammed.mp3',
      size: '9.4M',
      durationInSecs: 1232,
    },
    {
      index: 48,
      name: 'سورَة ٱلْفَتْح',
      nameTrans: 'Surah Al-Fath',
      nameMl: 'അല്‍ ഫത്ഹ്',
      fileName: '048_Al_Fathah.mp3',
      size: '10.4M',
      durationInSecs: 1359,
    },
    {
      index: 49,
      name: 'سورَة ٱلْحُجُرَات',
      nameTrans: 'Surah Al-Hujuraat',
      nameMl: 'അല്‍ ഹുജുറാത്',
      fileName: '049_Al_Hujurat.mp3',
      size: '6.5M',
      durationInSecs: 851,
    },
    {
      index: 50,
      name: 'سورَة ق',
      nameTrans: 'Surah Qaaf',
      nameMl: 'ഖാഫ്',
      fileName: '050_Qaf.mp3',
      size: '7.3M',
      durationInSecs: 956,
    },
    {
      index: 51,
      name: 'سورَة ٱلذَّارِيَات',
      nameTrans: 'Surah Adh-Dhaariyaat',
      nameMl: 'അദ്ദാരിയാത്',
      fileName: '051_Adh_Dhariyat.mp3',
      size: '6.7M',
      durationInSecs: 875,
    },
    {
      index: 52,
      name: 'سورَة ٱلطُّور',
      nameTrans: 'Surah At-Toor',
      nameMl: 'അത്ത്വൂര്‍',
      fileName: '052_At_Tur.mp3',
      size: '6.4M',
      durationInSecs: 875,
    },
    {
      index: 53,
      name: 'سورَة ٱلنَّجْم',
      nameTrans: 'Surah An-Najm',
      nameMl: 'അന്നജ്മ്',
      fileName: '053_Al_Najm.mp3',
      size: '7.1M',
      durationInSecs: 925,
    },
    {
      index: 54,
      name: 'سورَة ٱلْقَمَر',
      nameTrans: 'Surah Al-Qamar',
      nameMl: 'അല്‍ ഖമര്‍',
      fileName: '054_Al_Qamar.mp3',
      size: '7.5M',
      durationInSecs: 979,
    },
    {
      index: 55,
      name: 'سورَة ٱلرَّحْمَٰن',
      nameTrans: 'Surah Ar-Rahman',
      nameMl: 'അര്‍റഹ് മാന്‍‍',
      fileName: '055_Ar_Rahman.mp3',
      size: '9.3M',
      durationInSecs: 1222,
    },
    {
      index: 56,
      name: 'سورَة ٱلْوَاقِعَة',
      nameTrans: "Surah Al-Waqi'a",
      nameMl: 'അല്‍ വാഖിഅ',
      fileName: '056_Al_Waqia.mp3',
      size: '8.5M',
      durationInSecs: 1118,
    },
    {
      index: 57,
      name: 'سورَة ٱلْحَدِيد',
      nameTrans: 'Surah Al-Hadeed',
      nameMl: 'അല്‍ ഹദീദ്',
      fileName: '057_Al_Hadeeth.mp3',
      size: '10.9M',
      durationInSecs: 1430,
    },
    {
      index: 58,
      name: 'سورَة ٱلْمُجَادِلَة',
      nameTrans: 'Surah Al-Mujadila',
      nameMl: 'അല്‍ മുജാദിലഃ',
      fileName: '058_Al_Mujadillah.mp3',
      size: '8.1M',
      durationInSecs: 1056,
    },
    {
      index: 59,
      name: 'سورَة ٱلْحَشْر',
      nameTrans: 'Surah Al-Hashr',
      nameMl: 'അല്‍ ഹശ്ര്‍',
      fileName: '059_Al_Hashr.mp3',
      size: '8.1M',
      durationInSecs: 1067,
    },
    {
      index: 60,
      name: 'سورَة ٱلْمُمْتَحَنَة',
      nameTrans: 'Surah Al-Mumtahanah',
      nameMl: 'അല്‍ മുംതഹിനഃ',
      fileName: '060_Al_Mumthahana.mp3',
      size: '6.3M',
      durationInSecs: 825,
    },
    {
      index: 61,
      name: 'سورَة ٱلصَّفّ',
      nameTrans: 'Surah As-Saff',
      nameMl: 'അസ്സ്വഫ്ഫ്',
      fileName: '061_As_Saff.mp3',
      size: '4.0M',
      durationInSecs: 522,
    },
    {
      index: 62,
      name: 'سورَة ٱلْجُمُعَة',
      nameTrans: "Surah Al-Jumu'ah",
      nameMl: 'അല്‍ ജുമുഅഃ',
      fileName: '062_Al_Juma.mp3',
      size: '3.1M',
      durationInSecs: 401,
    },
    {
      index: 63,
      name: 'سورَة ٱلْمُنَافِقُون',
      nameTrans: 'Surah Al-Munafiqoon',
      nameMl: 'അല്‍ മുനാഫിഖൂന്‍',
      fileName: '063_Al_Munafiqoon.mp3',
      size: '3.1M',
      durationInSecs: 405,
    },
    {
      index: 64,
      name: 'سورَة ٱلتَّغَابُن',
      nameTrans: 'Surah At-Taghabun',
      nameMl: 'അല്‍ തഗാബൂന്‍',
      fileName: '064_At_Tagabun.mp3',
      size: '4.2M',
      durationInSecs: 546,
    },
    {
      index: 65,
      name: 'سورَة ٱلطَّلَاق',
      nameTrans: 'Surah At-Talaq',
      nameMl: 'അത്ത്വലാഖ്',
      fileName: '065_At_Talaq.mp3',
      size: '5.1M',
      durationInSecs: 672,
    },
    {
      index: 66,
      name: 'سورَة ٱلتَّحْرِيم',
      nameTrans: 'Surah At-Tahreem',
      nameMl: 'അത്തഹ് രീം',
      fileName: '066_At_Tahrim.mp3',
      size: '4.5M',
      durationInSecs: 590,
    },
    {
      index: 67,
      name: 'سورَة ٱلْمُلْك',
      nameTrans: 'Surah Al-Mulk',
      nameMl: 'അല്‍ മുല്‍ക്ക്',
      fileName: '067_Al_Mulk.mp3',
      size: '5.8M',
      durationInSecs: 759,
    },
    {
      index: 68,
      name: 'سورَة ٱلْقَلَم            ',
      nameTrans: 'Surah Al-Qalam',
      nameMl: 'അല്‍ ഖലം',
      fileName: '068_Al_Qalam.mp3',
      size: '6.1M',
      durationInSecs: 796,
    },
    {
      index: 69,
      name: 'سورَة ٱلْحَاقَّة            ',
      nameTrans: 'Surah Al-Haaqqa',
      nameMl: 'അല്‍ ഹാക്ക്വഃ',
      fileName: '069_Al-Haqa.mp3',
      size: '5.3M',
      durationInSecs: 688,
    },
    {
      index: 70,
      name: 'سورَة ٱلْمَعَارِج            ',
      nameTrans: "Surah Al-Ma'aarij",
      nameMl: 'അല്‍ മആരിജ്',
      fileName: '070_Al_Maarij.mp3',
      size: '4.4M ',
      durationInSecs: 577,
    },
    {
      index: 71,
      name: 'سورَة نُوح',
      nameTrans: 'Surah Nuh',
      nameMl: 'നൂഹ്',
      fileName: '071_Nooh.mp3',
      size: '4.3M',
      durationInSecs: 558,
    },
    {
      index: 72,
      name: 'سورَة ٱلْجِنّ            ',
      nameTrans: 'Surah Al-Jinn',
      nameMl: 'അല്‍ ജിന്ന്',
      fileName: '072_Al_Jinn.mp3',
      size: '5.1M',
      durationInSecs: 671,
    },
    {
      index: 73,
      name: 'سورَة ٱلْمُزَّمِّل            ',
      nameTrans: 'Surah Al-Muzzammil',
      nameMl: 'അല്‍ മുസമ്മില്‍',
      fileName: '073_Al_Muzzamil.mp3',
      size: '4.0M',
      durationInSecs: 522,
    },
    {
      index: 74,
      name: 'سورَة ٱلْمُدَّثِّر            ',
      nameTrans: 'Surah Al-Muddaththir',
      nameMl: 'അല്‍ മുദ്ദഥിര്‍',
      fileName: '074_Al_Mudathir.mp3',
      size: '4.9M',
      durationInSecs: 648,
    },
    {
      index: 75,
      name: 'سورَة ٱلْقِيَامَة',
      nameTrans: 'Surah Al-Qiyamah',
      nameMl: 'അല്‍ ഖിയാമഃ',
      fileName: '075_Al_Qiyama.mp3',
      size: '3.2M',
      durationInSecs: 419,
    },
    {
      index: 76,
      name: 'سورَة ٱلْإِنْسَان            ',
      nameTrans: 'Surah Al-Insaan',
      nameMl: 'അല്‍ ഇന്‍സാന്‍',
      fileName: '076_Al_Insan.mp3',
      size: '5.0M',
      durationInSecs: 652,
    },
    {
      index: 77,
      name: 'سورَة ٱلْمُرْسَلَات            ',
      nameTrans: 'Surah Al-Mursalaat',
      nameMl: 'അല്‍ മുര്‍സലാത്ത്',
      fileName: '077_Al_Mursalat.mp3',
      size: '4.1M',
      durationInSecs: 541,
    },
    {
      index: 78,
      name: 'سورَة ٱلنَّبَأ            ',
      nameTrans: "Surah An-Naba'",
      nameMl: 'അന്നബഉ്',
      fileName: '078_An_Naba.mp3',
      size: '4.0M',
      durationInSecs: 524,
    },
    {
      index: 79,
      name: 'سورَة ٱلنَّازِعَات            ',
      nameTrans: "Surah An-Naazi'aat",
      nameMl: 'അന്നാസിആത്ത്',
      fileName: '079_AN_Naasiat.mp3',
      size: '3.9M',
      durationInSecs: 511,
    },
    {
      index: 80,
      name: 'سورَة عَبَسَ',
      nameTrans: 'Surah Abasa',
      nameMl: 'അബസ',
      fileName: '080_Abasa.mp3',
      size: '3.2M',
      durationInSecs: 414,
    },
    {
      index: 81,
      name: 'سورَة ٱلتَّكْوِير',
      nameTrans: 'Surah At-Takweer',
      nameMl: 'അത്തക് വീര്‍',
      fileName: '081_At_Takweer.mp3',
      size: '2.2M',
      durationInSecs: 294,
    },
    {
      index: 82,
      name: 'سورَة ٱلْإِنْفِطَار',
      nameTrans: 'Surah Al-Infitar',
      nameMl: 'അല്‍ ഇന്‍ഫിത്വാര്‍',
      fileName: '082_Al_Infitar.mp3',
      size: '1.8M',
      durationInSecs: 231,
    },
    {
      index: 83,
      name: 'سورَة ٱلْمُطَفِّفِين            ',
      nameTrans: 'Surah Al-Mutaffifeen',
      nameMl: 'അല്‍ മുതഫ്ഫിഫീന്‍',
      fileName: '083_Al_Muthaffiffeen.mp3',
      size: '3.6M',
      durationInSecs: 470,
    },
    {
      index: 84,
      name: 'سورَة ٱلْإِنْشِقَاق',
      nameTrans: 'Surah Al-Inshiqaaq',
      nameMl: 'അല്‍ ഇന്‍ശിഖാഖ്',
      fileName: '084_Al_Inshiqaq.mp3',
      size: '2.4M',
      durationInSecs: 312,
    },
    {
      index: 85,
      name: 'سورَة ٱلْبُرُوج',
      nameTrans: 'Surah Al-Burooj',
      nameMl: 'അല്‍ ബുറൂജ്',
      fileName: '085_Al_Burooj.mp3',
      size: '2.4M',
      durationInSecs: 318,
    },
    {
      index: 86,
      name: 'سورَة ٱلطَّارِق',
      nameTrans: 'Surah At-Taariq',
      nameMl: 'അത്ത്വാരിഖ്',
      fileName: '086_At_Tariq.mp3',
      size: '1.5M',
      durationInSecs: 195,
    },
    {
      index: 87,
      name: 'سورَة ٱلْأَعْلَىٰ',
      nameTrans: "Surah Al-A'la",
      nameMl: 'അല്‍ അഅ് ലാ',
      fileName: '087_Al_Ala.mp3',
      size: '1.6M',
      durationInSecs: 212,
    },
    {
      index: 88,
      name: 'سورَة ٱلْغَاشِيَة',
      nameTrans: 'Surah Al-Ghaashiyah',
      nameMl: 'അല്‍ ഗാശിയഃ',
      fileName: '088_Al_Ghashiya.mp3',
      size: '2.1M',
      durationInSecs: 272,
    },
    {
      index: 89,
      name: 'سورَة ٱلْفَجْر',
      nameTrans: 'Surah Al-Fajr',
      nameMl: 'അല്‍ ഫജ്ര്‍',
      fileName: '089_Al_Fajr.mp3',
      size: '2.8M',
      durationInSecs: 364,
    },
    {
      index: 90,
      name: 'سورَة ٱلْبَلَد',
      nameTrans: 'Surah Al-Balad',
      nameMl: 'അല്‍ ബലദ്',
      fileName: '090_Al_Balad.mp3',
      size: '1.6M',
      durationInSecs: 212,
    },
    {
      index: 91,
      name: 'سورَة ٱلشَّمْس',
      nameTrans: 'Surah Ash-Shams',
      nameMl: 'അശ്ശംസ്',
      fileName: '091_Ash_Shams.mp3',
      size: '1.5M',
      durationInSecs: 195,
    },
    {
      index: 92,
      name: 'سورَة ٱللَّيْل',
      nameTrans: 'Surah Al-Layl',
      nameMl: 'അല്‍ലൈല്‍',
      fileName: '092_Al_Lail.mp3',
      size: '1.7M',
      durationInSecs: 228,
    },
    {
      index: 93,
      name: 'سورَة ٱلضُّحَىٰ',
      nameTrans: 'Surah Ad-Dhuha',
      nameMl: 'അള്ള്വുഹാ',
      fileName: '093_Adh_Dhuha.mp3',
      size: '1.0M',
      durationInSecs: 133,
    },
    {
      index: 94,
      name: 'سورَة ٱلشَّرْح',
      nameTrans: 'Surah Ash-Sharh',
      nameMl: 'അശ്ശര്‍ഹ്',
      fileName: '094_Ash_Sharh.mp3',
      size: '798.6K',
      durationInSecs: 102,
    },
    {
      index: 95,
      name: 'سورَة ٱلتِّين',
      nameTrans: 'Surah At-Tin',
      nameMl: 'അത്തീന്‍',
      fileName: '095_At_Tin.mp3',
      size: '923.7K',
      durationInSecs: 118,
    },
    {
      index: 96,
      name: 'سورَة ٱلْعَلَق',
      nameTrans: 'Surah Al-Alaq',
      nameMl: 'അല്‍ അലഖ്',
      fileName: '096_Al_Alaq.mp3',
      size: '1.6M',
      durationInSecs: 209,
    },
    {
      index: 97,
      name: 'سورَة ٱلْقَدْر',
      nameTrans: 'Surah Al-Qadr',
      nameMl: 'അല്‍ ഖദ്ര്‍',
      fileName: '097_Al_Qadr.mp3',
      size: '783.1K',
      durationInSecs: 100,
    },
    {
      index: 98,
      name: 'سورَة ٱلْبَيِّنَة',
      nameTrans: 'Surah Al-Bayyinahh',
      nameMl: 'അല്‍ ബയ്യിനഃ',
      fileName: '098_Al_Bayyinah.mp3',
      size: '1.8M',
      durationInSecs: 241,
    },
    {
      index: 99,
      name: 'سورَة ٱلزَّلْزَلَة',
      nameTrans: 'Surah Az-Zalzalah',
      nameMl: 'അല്‍ സല്‍സലഃ',
      fileName: '099_Al_Zalzalah.mp3',
      size: '962.7K',
      durationInSecs: 123,
    },
    {
      index: 100,
      name: 'سورَة ٱلْعَادِيَات',
      nameTrans: "Surah Al-'Adiyat",
      nameMl: 'അല്‍ ആദിയാത്',
      fileName: '100_Al_Adhiyat.mp3',
      size: '1.1M',
      durationInSecs: 141,
    },
    {
      index: 101,
      name: 'سورَة ٱلْقَارِعَة',
      nameTrans: "Surah Al-Qaari'ah",
      nameMl: 'അല്‍ ഖാരിഅ',
      fileName: '101_Al_Qaria.mp3',
      size: '978.6K',
      durationInSecs: 125,
    },
    {
      index: 102,
      name: 'سورَة ٱلتَّكَاثُر',
      nameTrans: 'Surah At-Takathur',
      nameMl: 'അത്തകാഥുര്‍',
      fileName: '102_At_Takazur.mp3',
      size: '876.7K',
      durationInSecs: 112,
    },
    {
      index: 103,
      name: 'سورَة ٱلْعَصْر',
      nameTrans: "Surah Al-'Asr",
      nameMl: 'അല്‍ അസ്വര്‍',
      fileName: '103_Al_Asr.mp3',
      size: '478.6K',
      durationInSecs: 61,
    },
    {
      index: 104,
      name: 'سورَة ٱلْهُمَزَة',
      nameTrans: 'Surah Al-Humazah',
      nameMl: 'അല്‍ ഹുമസഃ',
      fileName: '104_Al_Humaza.mp3',
      size: '915.7K',
      durationInSecs: 117,
    },
    {
      index: 105,
      name: 'سورَة ٱلْفِيل',
      nameTrans: 'Surah Al-Fil',
      nameMl: 'അല്‍ ഫീല്‍',
      fileName: '105_Al_Feel.mp3',
      size: '697.1K',
      durationInSecs: 89,
    },
    {
      index: 106,
      name: 'سورَة قُرَيْش',
      nameTrans: 'Surah Quraysh',
      nameMl: 'ഖുറൈഷ്',
      fileName: '106_Quraish.mp3',
      size: '595.7K',
      durationInSecs: 76,
    },
    {
      index: 107,
      name: 'سورَة ٱلْمَاعُون',
      nameTrans: "Surah Al-Maa'oon",
      nameMl: 'അല്‍ മാഊന്‍',
      fileName: '107_Al_Maoon.mp3',
      size: '791.2K',
      durationInSecs: 101,
    },
    {
      index: 108,
      name: 'سورَة ٱلْكَوْثَر',
      nameTrans: 'Surah Al-Kawthar',
      nameMl: 'അല്‍ കൌഥര്‍‍',
      fileName: '108_Al_Kouthar.mp3',
      size: '501.6K',
      durationInSecs: 64,
    },
    {
      index: 109,
      name: 'سورَة ٱلْكَافِرُون',
      nameTrans: 'Surah Al-Kaafiroon',
      nameMl: 'അല്‍ കാഫിറൂന്‍',
      fileName: '109_Al_Kafiroon.mp3',
      size: '689.2K',
      durationInSecs: 88,
    },
    {
      index: 110,
      name: 'سورَة ٱلنَّصْر',
      nameTrans: 'Surah An-Nasr',
      nameMl: 'അന്നസ്ര്‍',
      fileName: '110_An_Nasr.mp3',
      size: '619.2K',
      durationInSecs: 79,
    },
    {
      index: 111,
      name: 'سورَة ٱلْمَسَد',
      nameTrans: 'Surah Al-Masad',
      nameMl: 'അല്‍ മസദ്',
      fileName: '111_Al_Masad.mp3',
      size: '650.2K',
      durationInSecs: 83,
    },
    {
      index: 112,
      name: 'سورَة ٱلْإِخْلَاص',
      nameTrans: 'Surah Al-Ikhlaas',
      nameMl: 'അല്‍ ഇഖ് ലാസ്',
      fileName: '112_Al_Ikhlas.mp3',
      size: '478.6K',
      durationInSecs: 61,
    },
    {
      index: 113,
      name: 'سورَة ٱلْفَلَق',
      nameTrans: 'Surah Al-Falaq',
      nameMl: 'അല്‍ ഫലഖ്',
      fileName: '113_Al_Falaq.mp3',
      size: '595.7K',
      durationInSecs: 76,
    },
    {
      index: 114,
      name: 'سورَة ٱلنَّاس',
      nameTrans: 'Surah An-Naas',
      nameMl: 'അന്നാസ്',
      fileName: '114_An_Nass.mp3',
      size: '603.7K',
      durationInSecs: 77,
    },
  ],
};
