import type { QuranSurah } from './types';

const surahLoaders: Record<number, () => QuranSurah> = {
  1: () => require('@/assets/quran-json/1.json') as QuranSurah,
  2: () => require('@/assets/quran-json/2.json') as QuranSurah,
  3: () => require('@/assets/quran-json/3.json') as QuranSurah,
  4: () => require('@/assets/quran-json/4.json') as QuranSurah,
  5: () => require('@/assets/quran-json/5.json') as QuranSurah,
  6: () => require('@/assets/quran-json/6.json') as QuranSurah,
  7: () => require('@/assets/quran-json/7.json') as QuranSurah,
  8: () => require('@/assets/quran-json/8.json') as QuranSurah,
  9: () => require('@/assets/quran-json/9.json') as QuranSurah,
  10: () => require('@/assets/quran-json/10.json') as QuranSurah,
  11: () => require('@/assets/quran-json/11.json') as QuranSurah,
  12: () => require('@/assets/quran-json/12.json') as QuranSurah,
  13: () => require('@/assets/quran-json/13.json') as QuranSurah,
  14: () => require('@/assets/quran-json/14.json') as QuranSurah,
  15: () => require('@/assets/quran-json/15.json') as QuranSurah,
  16: () => require('@/assets/quran-json/16.json') as QuranSurah,
  17: () => require('@/assets/quran-json/17.json') as QuranSurah,
  18: () => require('@/assets/quran-json/18.json') as QuranSurah,
  19: () => require('@/assets/quran-json/19.json') as QuranSurah,
  20: () => require('@/assets/quran-json/20.json') as QuranSurah,
  21: () => require('@/assets/quran-json/21.json') as QuranSurah,
  22: () => require('@/assets/quran-json/22.json') as QuranSurah,
  23: () => require('@/assets/quran-json/23.json') as QuranSurah,
  24: () => require('@/assets/quran-json/24.json') as QuranSurah,
  25: () => require('@/assets/quran-json/25.json') as QuranSurah,
  26: () => require('@/assets/quran-json/26.json') as QuranSurah,
  27: () => require('@/assets/quran-json/27.json') as QuranSurah,
  28: () => require('@/assets/quran-json/28.json') as QuranSurah,
  29: () => require('@/assets/quran-json/29.json') as QuranSurah,
  30: () => require('@/assets/quran-json/30.json') as QuranSurah,
  31: () => require('@/assets/quran-json/31.json') as QuranSurah,
  32: () => require('@/assets/quran-json/32.json') as QuranSurah,
  33: () => require('@/assets/quran-json/33.json') as QuranSurah,
  34: () => require('@/assets/quran-json/34.json') as QuranSurah,
  35: () => require('@/assets/quran-json/35.json') as QuranSurah,
  36: () => require('@/assets/quran-json/36.json') as QuranSurah,
  37: () => require('@/assets/quran-json/37.json') as QuranSurah,
  38: () => require('@/assets/quran-json/38.json') as QuranSurah,
  39: () => require('@/assets/quran-json/39.json') as QuranSurah,
  40: () => require('@/assets/quran-json/40.json') as QuranSurah,
  41: () => require('@/assets/quran-json/41.json') as QuranSurah,
  42: () => require('@/assets/quran-json/42.json') as QuranSurah,
  43: () => require('@/assets/quran-json/43.json') as QuranSurah,
  44: () => require('@/assets/quran-json/44.json') as QuranSurah,
  45: () => require('@/assets/quran-json/45.json') as QuranSurah,
  46: () => require('@/assets/quran-json/46.json') as QuranSurah,
  47: () => require('@/assets/quran-json/47.json') as QuranSurah,
  48: () => require('@/assets/quran-json/48.json') as QuranSurah,
  49: () => require('@/assets/quran-json/49.json') as QuranSurah,
  50: () => require('@/assets/quran-json/50.json') as QuranSurah,
  51: () => require('@/assets/quran-json/51.json') as QuranSurah,
  52: () => require('@/assets/quran-json/52.json') as QuranSurah,
  53: () => require('@/assets/quran-json/53.json') as QuranSurah,
  54: () => require('@/assets/quran-json/54.json') as QuranSurah,
  55: () => require('@/assets/quran-json/55.json') as QuranSurah,
  56: () => require('@/assets/quran-json/56.json') as QuranSurah,
  57: () => require('@/assets/quran-json/57.json') as QuranSurah,
  58: () => require('@/assets/quran-json/58.json') as QuranSurah,
  59: () => require('@/assets/quran-json/59.json') as QuranSurah,
  60: () => require('@/assets/quran-json/60.json') as QuranSurah,
  61: () => require('@/assets/quran-json/61.json') as QuranSurah,
  62: () => require('@/assets/quran-json/62.json') as QuranSurah,
  63: () => require('@/assets/quran-json/63.json') as QuranSurah,
  64: () => require('@/assets/quran-json/64.json') as QuranSurah,
  65: () => require('@/assets/quran-json/65.json') as QuranSurah,
  66: () => require('@/assets/quran-json/66.json') as QuranSurah,
  67: () => require('@/assets/quran-json/67.json') as QuranSurah,
  68: () => require('@/assets/quran-json/68.json') as QuranSurah,
  69: () => require('@/assets/quran-json/69.json') as QuranSurah,
  70: () => require('@/assets/quran-json/70.json') as QuranSurah,
  71: () => require('@/assets/quran-json/71.json') as QuranSurah,
  72: () => require('@/assets/quran-json/72.json') as QuranSurah,
  73: () => require('@/assets/quran-json/73.json') as QuranSurah,
  74: () => require('@/assets/quran-json/74.json') as QuranSurah,
  75: () => require('@/assets/quran-json/75.json') as QuranSurah,
  76: () => require('@/assets/quran-json/76.json') as QuranSurah,
  77: () => require('@/assets/quran-json/77.json') as QuranSurah,
  78: () => require('@/assets/quran-json/78.json') as QuranSurah,
  79: () => require('@/assets/quran-json/79.json') as QuranSurah,
  80: () => require('@/assets/quran-json/80.json') as QuranSurah,
  81: () => require('@/assets/quran-json/81.json') as QuranSurah,
  82: () => require('@/assets/quran-json/82.json') as QuranSurah,
  83: () => require('@/assets/quran-json/83.json') as QuranSurah,
  84: () => require('@/assets/quran-json/84.json') as QuranSurah,
  85: () => require('@/assets/quran-json/85.json') as QuranSurah,
  86: () => require('@/assets/quran-json/86.json') as QuranSurah,
  87: () => require('@/assets/quran-json/87.json') as QuranSurah,
  88: () => require('@/assets/quran-json/88.json') as QuranSurah,
  89: () => require('@/assets/quran-json/89.json') as QuranSurah,
  90: () => require('@/assets/quran-json/90.json') as QuranSurah,
  91: () => require('@/assets/quran-json/91.json') as QuranSurah,
  92: () => require('@/assets/quran-json/92.json') as QuranSurah,
  93: () => require('@/assets/quran-json/93.json') as QuranSurah,
  94: () => require('@/assets/quran-json/94.json') as QuranSurah,
  95: () => require('@/assets/quran-json/95.json') as QuranSurah,
  96: () => require('@/assets/quran-json/96.json') as QuranSurah,
  97: () => require('@/assets/quran-json/97.json') as QuranSurah,
  98: () => require('@/assets/quran-json/98.json') as QuranSurah,
  99: () => require('@/assets/quran-json/99.json') as QuranSurah,
  100: () => require('@/assets/quran-json/100.json') as QuranSurah,
  101: () => require('@/assets/quran-json/101.json') as QuranSurah,
  102: () => require('@/assets/quran-json/102.json') as QuranSurah,
  103: () => require('@/assets/quran-json/103.json') as QuranSurah,
  104: () => require('@/assets/quran-json/104.json') as QuranSurah,
  105: () => require('@/assets/quran-json/105.json') as QuranSurah,
  106: () => require('@/assets/quran-json/106.json') as QuranSurah,
  107: () => require('@/assets/quran-json/107.json') as QuranSurah,
  108: () => require('@/assets/quran-json/108.json') as QuranSurah,
  109: () => require('@/assets/quran-json/109.json') as QuranSurah,
  110: () => require('@/assets/quran-json/110.json') as QuranSurah,
  111: () => require('@/assets/quran-json/111.json') as QuranSurah,
  112: () => require('@/assets/quran-json/112.json') as QuranSurah,
  113: () => require('@/assets/quran-json/113.json') as QuranSurah,
  114: () => require('@/assets/quran-json/114.json') as QuranSurah,
};

const cache = new Map<number, QuranSurah>();

export function getQuranSurah(chapterIndex: number): QuranSurah {
  const cached = cache.get(chapterIndex);
  if (cached) return cached;
  const loader = surahLoaders[chapterIndex];
  if (!loader) {
    throw new Error(`Unknown surah index: ${chapterIndex}`);
  }
  const surah = loader();
  cache.set(chapterIndex, surah);
  return surah;
}
